### ISSUE TITLE
[DStability] Bug in sorting of stages if no. stages >10

### ISSUE THREAD

**Issue by Daniel2511** [Deltares/GEOLib#113]
A d-stability stix-file is parsed in dstability_parserprovider.py. The order of the stages is maintained by sorting the file names. However if there are 11 or more stages then the stage order gets mixed-up because when sorting strings the '10' will be placed after '1'.

**Comment by carloslubbers** [comment]
This issue may be fixed by accident in the upcoming 2023.01 release of D-Stability due to a change in the project file format. All stages will be written to a single file so their order will no longer depend on the filename in the ZIP archive. A fix for the current version, if critical, would be to use a more "natural" sort algorithm instead of the standard sort
