### ISSUE TITLE
Bug in parsing sheet piling using SheetPiling.parse_text

### ISSUE THREAD

**Issue by BTGAlgemeen** [Deltares/GEOLib#119]
GEOLib version 1.0.0

When trying to parse the sheet piling data as generated by the DSheetPilingStructure().parse_text("input file").input_data.sheet_piling to a SheetPiling instance using SheetPiling.parse_text(), Python throws a ValueError. This is due to the fact that the SheetPiling superclass (DSeriesStructureCollection) parse_text function allows for 1 field in the collection, while a SheetPiling defines 3. So irrespective of the input a ValueError is raised because len(fields) != 1 with fields = [('sheetpiling', <class 'types.ConstrainedListValue'>), ('leveltopsheetpiling', <class 'geolib.models.dsheetpiling.internal.ConstrainedFloatValue'>), ('lengthsheetpiling', <class 'geolib.models.dsheetpiling.internal.ConstrainedFloatValue'>)]

```
from geolib.models.dsheetpiling.internal import DSheetPilingStructure, SheetPileElement, SheetPiling
        
        with open(self.path + self.file) as f:
            text = f.read()

        d_sheet_file = DSheetPilingStructure.parse_text(text)

        sheet_text = d_sheet_file.input_data.sheet_piling
        sheet = SheetPiling.parse_text(sheet_text)


File "C:\Users\..\main.py", line 91, in read_file
        sheet = SheetPiling.parse_text(sheet_text)
File "C:\Users\..\lib\site-packages\geolib\models\dseries_parser.py", line 725, in parse_text
        raise ValueError(
ValueError: This type of collection is only meant to have one field but 3 were defined.
```

**Comment by VirginieTrompille** [comment]
We can indeed reproduce this bug. SheetPiling uses the parser of DSeriesStructure to parse the block SHEET PILING. This parser expects only one line before the block SHEET PILING ELEMENT (the number of elements) but the  SHEET PILING block contains 2 extra input parameters (LevelTopSheetPiling and Length) as you can see below.
That's why an error message is returned.
We will try to fix this bug in a short term. 
You can also solve it yourself with a pull request.
-------------------------------------------------------
[SHEET PILING]
0
     10.00 Level top sheet piling
     20.00 Length
  1 Number of elements
[SHEET PILING ELEMENT]
Beam
SheetPilingElementMaterialType=1
... etc

**Comment by zantDelta** [comment]
Best way to fix this would be to improve the structure of the block in the inputfile. That would require a change in DSheetPiling. I created an issue MSH-4894 for that.
