### ISSUE TITLE
Can't get D-Settlement console to run

### ISSUE THREAD

**Issue by geodig** [Deltares/GEOLib#147]
I have placed the D-Settlement console in a folder (which is written in an *.env file), but everytime I try to execute the D-Settlement model, a window opens with the following error message: 
"License not granted
Module(s) not found in the license file or borrowed modules, or license file not found.
Batch processing not allowed."

How to solve this?

**Comment by bstthe** [comment]
Did you install the consoles as was described in https://deltares.github.io/GEOLib/latest/user/setup.html#console-usage Iseection "Consoles") and did you obtain a license from Deltares and installed it?

**Comment by geodig** [comment]
Yes I did. Yesterday I contacted Deltares and they give me the license file and I install it using "Add License File" program but it still gives me an error during executing the model using geolib. This time it gives the following error "Output file generated but parsing of Tutorial.sld failed"

**Comment by bstthe** [comment]
The good news is that your system is working now. It seems however that the calculation was not successful. Check if the model that you created with GEOLib is correct. Did you study the tutorial (https://deltares.github.io/GEOLib/latest/community/tutorial_dsettlement.html)?

**Comment by geodig** [comment]
I did. In fact, I followed the tutorial step-by-step as in the link that you shared

**Comment by zantDelta** [comment]
I see that the inputfile (sli) is created with GEOLib version 0.2.3 and the output file with D-Settlement version 21.2.1.34213.
Currently GEOLib works only with DSettlementConsole.exe version 19.1 (build 1.34009), see https://deltares.github.io/GEOLib/latest/user/setup.html. 
At the end of this year we will release DSettlement 23.2 and update the GEOLib code to work with that version.
I am not sure about GEOLib version 0.2.3 but when you get the latest changes from the master you will get GEOLib version 1.3.1. If you follow the tutorial with the current master and run with DSettlementConsole.exe version 19.1.1.34009 it should succeed. Please notice that for DSettlementConsole.exe version 19.1 you need a different license file than for the regular DSettlement.exe. Your company (as I see in the sld file) should have this license, since it participated in the GEOLib project. If you do not have DSettlementConsole.exe version 19.1 yet, you can download it from https://download.deltares.nl/geolib

**Comment by geodig** [comment]
Hi @zantDelta, which license file that you mean? Last week I contacted Deltares software support, and they give me 100389_S_00505696b3cd.lic but it still doesn't work. The license file that I got from https://download.deltares.nl/en/license-manager also doesn't work either. Upgrading to geolib v1.3.1 doesn't help either, so it must be really the problem of license.

**Comment by zantDelta** [comment]
Please ask Deltares software support for a license of DSettlementConsole.exe version 19.1

**Comment by zantDelta** [comment]
I presume the problem was solved, so I close this issue
