### ISSUE TITLE
console_path for d-sheet console

### ISSUE THREAD

**Issue by ChristianRasch** [Deltares/GEOLib#149]
In the D-Sheet model (dsheetpiling_model.py) the console path is set to:

return Path("DSheetPiling/DSheetPiling.exe")

However, the default directory for installation of the DSheet Piling v23 consoles/executables is different. These are installed with

D-Sheet Piling 23.1.1/DSheetPiling.exe

Temporary workaround is now changing this line in the installed geolib module.

Is this a bug, or can the actual folder of the executables be specified in the geolib.env file as well? According to the documentation (and code) it is to be excpected in the folder DSheetPiling/ instead of D-Sheet Piling 23.1.1/

**Comment by ChristianRasch** [comment]
Thank you for your answer. Would it be an idea to add the ability to specify this folder in the geolib.env file? The default value would then be DSheetPiling/.
Workarounds with new folders in the Program Files directory is not ideal, especially when creating tools for colleagues who do not have any rights on that directory.

**Comment by carloslubbers** [comment]
We have some ideas to make the paths to calculation consoles easier to configure in the env file in the short term. It may be an option to offer additional settings to set a path directly, instead of all consoles being discovered through the CONSOLE_FOLDER. That would get us options like DSHEETPILING_CONSOLE_PATH to set it directly

**Comment by carloslubbers** [comment]
@ChristianRasch These new parameters will be implemented by PR #165

**Comment by wfaustmann** [comment]
Closing this issue as it is fixed in Pr #165
