### ISSUE TITLE
Issue(DStability): Soil visualizations change after geolib.models.DStabilityModel().execute()

### ISSUE THREAD

**Issue by Deformance** [Deltares/GEOLib#30]
**Version**
0.2.0

**Issue:**
After creating a model using GEOlib, going through serialization and then execution of said model, the soil visualizations are (seemingly) all reset to default and/or made equal to one visualization. This behaviour does not happen when `geolib.models.DStabilityModel().execute()` is skipped, see the attached images.

**Serialized model opened in D-Stability excluding running `geolib.models.DStabilityModel().execute()`**
![image](https://user-images.githubusercontent.com/26150054/198302150-a3caf99d-a048-4ced-809c-6fde8597ab1c.png)

**Serialized model opened in D-Stability including running `geolib.models.DStabilityModel().execute()`**
![image](https://user-images.githubusercontent.com/26150054/198302255-11603e48-5ab2-4220-8dd3-2d4ceaf7cc08.png)

**Steps to Reproduce**
1. Set up a DStability-model using GEOLib.
2. `geolib.models.DStabilityModel().serialize()` the created model.
3. Check the soil visualizations.
4. `geolib.models.DStabilityModel().execute()` the created model.
5. Check the soil visualizations.
6. Compare output of steps 2 and 4.

**Comment by carloslubbers** [comment]
Hello, thank you for your issue report! This issue seems to be caused by a difference in behavior between the D-Stability User Interface and the D-Stability Console (used by GEOLib).

GEOLib does not assign any color or shading types to Soils in the model by default, unless the code explicitly does so, for example:
`for soil in dm.soils.Soils:
            dm.datastructure.soilvisualizations.SoilVisualizations.append(PersistableSoilVisualization(SoilId=soil.Id, Color="#ff2b5580", PersistableShadingType=PersistableShadingType.DOT_A))`

Thus, a .stix file generated by .serialize() has no soil visualizations configured.

When you open this file in the D-Stability User Interface, the user interface will notice no visualizations have been set and it will generate some based on the volumetric weight.

Your confusing situation is caused by the D-Stability Console, which does not offer this automatic generation of visualizations and will just set them to the default presentation, calculate the file and saves it to the disk again with defaults set. I would agree this is confusing and I will notify the D-Stability team of this, we may be able to improve this in the future.

For now, GEOLib is working as expected, but a fix in the application itself would be nice to have in the future. I recommend you manually set colors as needed using the example above as a workaround in the meantime!

**Comment by Deformance** [comment]
That clears it up! 
Thank you kindly for the adequate and timely response. Consider this issue 'resolved' but we're glad to hear this feedback is being shared with the D-Stability team.
